---

- name: install haproxy
  yum: name=haproxy state=latest

- name: enable haproxy service
  service:
    name: haproxy
    enabled: yes
- name: start haproxy
  service:
    name: haproxy
    state: restarted

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    # notify:
    #- restart haproxy

- name: start haproxy
  service:
    name: haproxy
    state: started

    #handlers:
    #- name: restart haproxy
    #service:
    #  name: haproxy
    #  state: restarted
