---
- name: deploy apache
  hosts: apps
  become: true

  tasks:
  - name: install apache
    yum: 
      name=httpd state=latest
  
  - name: enable apache
    service:
      name: httpd
      enabled: yes

  - name: start httpd service
    service:
      name: httpd
      state: started


