---
- name: deploy common repos
  hosts: frontends,apps,appdbs
  become: yes
  roles:
    - {role: common, tags: [ 'common' ]}
    - {role: http-client, tags: [ 'common' ]}

- name: deploy haproxy
  hosts: frontends
  become: yes
  roles: 
    - {role: haproxy, tags: [ 'lb','haproxy' ]}
  
- name: deploy appservers
  hosts: apps
  become: yes
  roles: 
    - {role: appserver, tags: [ 'appserver' ]}
- name: deploy postgres
  hosts: appdbs
  become: yes
  roles:
    - {role: geerlingguy.postgresql, tags: [ 'db','postgres' ]}
      
